dist: xenial
language: scala

scala:
- 2.11.12
- 2.12.10
- 2.13.1

jdk:
- openjdk8

before_install:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc
   -K $encrypted_37b99bd39158_key -iv $encrypted_37b99bd39158_iv
   -in secring.gpg.enc -out secring.gpg -d; fi
- export PATH=${PATH}:./vendor/bundle

install:
- rvm use 2.3.0 --install --fuzzy
- gem install sass
- gem install jekyll -v 3.2.1

script:
- sbt ++$TRAVIS_SCALA_VERSION orgScriptCI
- sbt 'examples/test:compile'

jobs:
  include:
    - stage: deploy
      script:
        - bash <(curl -s https://codecov.io/bash)
        - sbt ++$TRAVIS_SCALA_VERSION orgAfterCISuccess
      scala: 2.13.1

services:
- redis-server
